services:
  client:
    build: client/
    restart: always
    ports:
      - 3000:3000
    links:
      - server
    command: yarn start:client

  server:
    build: server/
    restart: always
    ports:
      - 4000:4000
    command: yarn dev