services:
  client:
    build: ./
    restart: always
    ports:
      - 3000:3000
    volumes:
      - ./:/client
      - /client/node_modules
    links:
      - server
    networks:
      - appnetwork

  server:
    build: server/
    restart: always
    ports:
      - 4000:4000
    volumes:
      - ./server:/server
      - /server/node_modules
    networks:
      - appnetwork

networks:
  appnetwork:
    driver: bridge